swagger: '2.0'
info:
  description: >
    API description for  lang-import backend - cached translations to any language
  version: 0.1.6
  title: translate-backend
  contact:
    email: owner@reddec.net
host: 0.0.0.0:8888
basePath: /
schemes:
  - http
paths:
  /translate/{word}/to/{lang}:
    get:
      summary: Translate (or get from cache) specified word to specified language
      description: ''
      operationId: Translate
      parameters:
        - in: path
          required: yes
          name: word
          type: string
          description: Word to translate
        - in: path
          required: yes
          name: word
          type: string
          description: Word to translate

      produces:
        - text/plain
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              type: string


externalDocs:
  url: 'https://github.com/lang-import/translate-backend'
